apiVersion: platform.local.lab/v1alpha1
kind: Wordpress
metadata:
  name: kentjarrett-com
spec:
  parameters:
    host: kentjarrett.com
    storageSize: "10Gi"
    dbStorageSize: "2Gi"
    replicas: 1
    size: md
    dataRetention: retain
