apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-mirror-writer
  namespace: guest-electric-cannon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-mirror-writer
subjects:
  - kind: ServiceAccount
    name: secret-mirror-controller
    namespace: secret-mirror-controller
