apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: cosmic-pirate-api
spec:
  parameters:
    namespace: guest-cosmic-pirate
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo5-api.mattjarrett.dev
    tlsSecret: demo5-api-tls
    sqlRef:
      name: cosmic-pirate-sql
      backend: private-cloud
    nosqlRef:
      name: cosmic-pirate-nosql
    objectStorageRefs:
      - name: cosmic-pirate-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
