apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-electric-spreadsheet
spec:
  parameters:
    namespace: guest-electric-spreadsheet
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo5-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-electric-spreadsheet
    objectStorageRef:
      name: xobjectstorage-electric-spreadsheet
    readinessCheckPath: /readyz
