apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-banana-pickle
spec:
  parameters:
    namespace: guest-banana-pickle
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    nosqlRef:
      name: xnosql-banana-pickle
    cache:
      enabled: true
    readinessCheckPath: /readyz
