apiVersion: platform.local.lab/v1alpha1
kind: XWordpress
metadata:
  name: mattjarrett-com
spec:
  parameters:
    host: mattjarrett.com
    storageSize: "7Gi"
    dbStorageSize: "1Gi"
    replicas: 1
    cpuRequest: "250m"
    cpuLimit: "1500m"
    memoryRequest: "512Mi"
    memoryLimit: "1024Mi"
    dataRetention: retain
