apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: rubber-burrito-api
spec:
  parameters:
    namespace: guest-rubber-burrito
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo2-api.mattjarrett.dev
    tlsSecret: demo2-api-tls
    sqlRef:
      name: rubber-burrito-sql
      backend: private-cloud
    nosqlRef:
      name: rubber-burrito-nosql
    objectStorageRefs:
      - name: rubber-burrito-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
