apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: api
spec:
  parameters:
    namespace: guest-midnight-burrito
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo1-api.mattjarrett.dev
    tlsSecret: demo1-api-tls
    sqlRef:
      name: sql
      backend: private-cloud
    nosqlRef:
      name: nosql
    objectStorageRefs:
      - name: store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
