apiVersion: platform.local.lab/v1alpha1
kind: XSql
metadata:
  name: midnight-burrito-sql
spec:
  parameters:
    namespace: guest-midnight-burrito
    backend: private-cloud
    dataRetention: delete
