apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-neon-catapult
spec:
  parameters:
    namespace: guest-neon-catapult
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo1-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-neon-catapult
    objectStorageRef:
      name: xobjectstorage-neon-catapult
    cache:
      enabled: true
