apiVersion: platform.local.lab/v1alpha1
kind: XSql
metadata:
  name: midnight-tornado-sql
spec:
  parameters:
    namespace: guest-midnight-tornado
    backend: private-cloud
    dataRetention: delete
