apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-exploding-cassette
spec:
  parameters:
    namespace: guest-exploding-cassette
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    objectStorageRef:
      name: xobjectstorage-exploding-cassette
    cache:
      enabled: true
