apiVersion: platform.local.lab/v1alpha1
kind: XSql
metadata:
  name: xsql-rubber-cassette
spec:
  parameters:
    namespace: guest-rubber-cassette
    backend: private-cloud
    dataRetention: delete
