apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: disco-pirate-api
spec:
  parameters:
    namespace: guest-disco-pirate
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsSecret: demo4-api-tls
    nosqlRef:
      name: disco-pirate-nosql
    objectStorageRefs:
      - name: disco-pirate-store
    readinessCheckPath: /readyz
