apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-phantom-spatula
spec:
  parameters:
    namespace: guest-phantom-spatula
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo1-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    readinessCheckPath: /readyz
