apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-shadow-cactus
spec:
  parameters:
    namespace: guest-shadow-cactus
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo5-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-shadow-cactus
      backend: private-cloud
    readinessCheckPath: /readyz
