apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-shadow-wizard
spec:
  parameters:
    namespace: guest-shadow-wizard
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsSecret: demo3-api-tls
    readinessCheckPath: /readyz
