apiVersion: v1
kind: Namespace
metadata:
  name: guest-laser-hamster
  labels:
    launchpad.local.lab/slot: demo5
    platform.local.lab/workloads: "true"
    istio-injection: enabled
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
