apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-turbo-factory
spec:
  parameters:
    namespace: guest-turbo-factory
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-turbo-factory
      backend: private-cloud
    nosqlRef:
      name: xnosql-turbo-factory
    objectStorageRefs:
      - name: xobjectstorage-turbo-factory
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
