apiVersion: platform.local.lab/v1alpha1
kind: Spa
metadata:
  name: connections-demo
  namespace: platform-connections-demo
spec:
  parameters:
    image: ghcr.io/cujarrett/platform-connections-demo-spa:sha-9770cd38daafb065f6436d6ef1b00f57526b47a0
    repo: https://github.com/cujarrett/platform-connections-demo
    host: connections.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    replicas: 1
    size: xs
    contentSecurityPolicy: "default-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self';"
    apiProxies:
      - path: /authorized/
        app: authorized-api
      - path: /unauthorized/
        app: unauthorized-api
