apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: phantom-pretzel-api
spec:
  parameters:
    namespace: guest-phantom-pretzel
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo5-api.mattjarrett.dev
    tlsSecret: demo5-api-tls
    sqlRef:
      name: phantom-pretzel-sql
      backend: private-cloud
    nosqlRef:
      name: phantom-pretzel-nosql
    objectStorageRefs:
      - name: phantom-pretzel-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
