apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: rubber-jelly-api
spec:
  parameters:
    namespace: guest-rubber-jelly
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsSecret: demo3-api-tls
    sqlRef:
      name: rubber-jelly-sql
      backend: private-cloud
    nosqlRef:
      name: rubber-jelly-nosql
    objectStorageRefs:
      - name: rubber-jelly-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
