apiVersion: platform.local.lab/v1alpha1
kind: XSpa
metadata:
  name: xspa-golden-factory
spec:
  parameters:
    namespace: guest-golden-factory
    image: ghcr.io/cujarrett/hello-world-spa:latest
    host: demo4.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    replicas: 1
    contentSecurityPolicy: default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self' https://*.mattjarrett.dev; frame-ancestors 'none'; base-uri 'self';
