apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: magic-pretzel-api
spec:
  parameters:
    namespace: guest-magic-pretzel
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsSecret: demo4-api-tls
    sqlRef:
      name: magic-pretzel-sql
      backend: private-cloud
    nosqlRef:
      name: magic-pretzel-nosql
    objectStorageRefs:
      - name: magic-pretzel-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
