apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: neon-penguin-api
spec:
  parameters:
    namespace: guest-neon-penguin
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo1-api.mattjarrett.dev
    tlsSecret: demo1-api-tls
    sqlRef:
      name: neon-penguin-sql
      backend: private-cloud
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
