apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-ceef
spec:
  parameters:
    namespace: guest-shadow-volcano
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    topicRef:
      name: xtopic-a3ae
    cache:
      enabled: true
