apiVersion: platform.local.lab/v1alpha1
kind: XTopic
metadata:
  name: xtopic-a3ae
spec:
  parameters:
    streamName: XTOPIC_A3AE
    subjects:
      - xtopic-a3ae.*
    retention: limits
    maxAge: 720h
    replicas: 3
