apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: fuzzy-cannon-api
spec:
  parameters:
    namespace: guest-fuzzy-cannon
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsSecret: demo3-api-tls
    sqlRef:
      name: fuzzy-cannon-sql
      backend: private-cloud
    nosqlRef:
      name: fuzzy-cannon-nosql
    objectStorageRefs:
      - name: fuzzy-cannon-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
