apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-laser-napkin
spec:
  parameters:
    namespace: guest-laser-napkin
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsSecret: demo3-api-tls
    nosqlRef:
      name: xnosql-laser-napkin
    objectStorageRefs:
      - name: xobjectstorage-laser-napkin
    readinessCheckPath: /readyz
