apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-disco-catapult
spec:
  parameters:
    namespace: guest-disco-catapult
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo5-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-disco-catapult
    objectStorageRef:
      name: xobjectstorage-disco-catapult
    readinessCheckPath: /readyz
