apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-velvet-catapult
spec:
  parameters:
    namespace: guest-velvet-catapult
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo2-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-velvet-catapult
      backend: private-cloud
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
