apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-midnight-jellybean
spec:
  parameters:
    namespace: guest-midnight-jellybean
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-midnight-jellybean
    objectStorageRef:
      name: xobjectstorage-midnight-jellybean
    cache:
      enabled: true
