apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: jazzy-spatula-api
spec:
  parameters:
    namespace: guest-jazzy-spatula
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsSecret: demo4-api-tls
    readinessCheckPath: /readyz
