apiVersion: v1
kind: Namespace
metadata:
  name: guest-silver-rocket
  labels:
    launchpad.local.lab/slot: demo2
  annotations:
    linkerd.io/inject: enabled
    argocd.argoproj.io/sync-wave: "-1"
