apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: haunted-waffle-api
spec:
  parameters:
    namespace: guest-haunted-waffle
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsSecret: demo4-api-tls
    sqlRef:
      name: haunted-waffle-sql
      backend: private-cloud
    nosqlRef:
      name: haunted-waffle-nosql
    objectStorageRefs:
      - name: haunted-waffle-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
