apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-golden-catapult
spec:
  parameters:
    namespace: guest-golden-catapult
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo5-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-golden-catapult
    cache:
      enabled: true
    readinessCheckPath: /readyz
