apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-turbo-submarine
spec:
  parameters:
    namespace: guest-turbo-submarine
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo1-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-turbo-submarine
    cache:
      enabled: true
    readinessCheckPath: /readyz
