apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: laser-waffle-api
spec:
  parameters:
    namespace: guest-laser-waffle
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsSecret: demo3-api-tls
    sqlRef:
      name: laser-waffle-sql
      backend: private-cloud
    nosqlRef:
      name: laser-waffle-nosql
    objectStorageRefs:
      - name: laser-waffle-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
