apiVersion: platform.local.lab/v1alpha1
kind: XSpa
metadata:
  name: xspa-a2ba
spec:
  parameters:
    namespace: guest-blue-catapult
    image: ghcr.io/cujarrett/hello-world-api:latest
    host: demo1.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    replicas: 1
