apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-laser-anvil
spec:
  parameters:
    namespace: guest-laser-anvil
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsSecret: demo3-api-tls
    sqlRef:
      name: xsql-laser-anvil
      backend: private-cloud
    nosqlRef:
      name: xnosql-laser-anvil
    objectStorageRefs:
      - name: xobjectstorage-laser-anvil
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
