apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: silver-jelly-api
spec:
  parameters:
    namespace: guest-silver-jelly
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo2-api.mattjarrett.dev
    tlsSecret: demo2-api-tls
    sqlRef:
      name: silver-jelly-sql
      backend: private-cloud
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
