apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-silver-volcano
spec:
  parameters:
    namespace: guest-silver-volcano
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-silver-volcano
    cache:
      enabled: true
    readinessCheckPath: /readyz
