apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-golden-llama
spec:
  parameters:
    namespace: guest-golden-llama
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-golden-llama
      backend: private-cloud
    nosqlRef:
      name: xnosql-golden-llama
    objectStorageRefs:
      - name: xobjectstorage-golden-llama
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
