apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: velvet-penguin-api
spec:
  parameters:
    namespace: guest-velvet-penguin
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsSecret: demo3-api-tls
    sqlRef:
      name: velvet-penguin-sql
      backend: private-cloud
    nosqlRef:
      name: velvet-penguin-nosql
    objectStorageRefs:
      - name: velvet-penguin-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
