apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-atomic-pirate
spec:
  parameters:
    namespace: guest-atomic-pirate
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsSecret: demo3-api-tls
    nosqlRef:
      name: xnosql-atomic-pirate
    objectStorageRefs:
      - name: xobjectstorage-atomic-pirate
    readinessCheckPath: /readyz
