apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-shadow-submarine
spec:
  parameters:
    namespace: guest-shadow-submarine
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-shadow-submarine
    nosqlRef:
      name: xnosql-shadow-submarine
    objectStorageRef:
      name: xobjectstorage-shadow-submarine
    cache:
      enabled: true
    readinessCheckPath: /readyz
