apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: electric-anvil-api
spec:
  parameters:
    namespace: guest-electric-anvil
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsSecret: demo3-api-tls
    sqlRef:
      name: electric-anvil-sql
      backend: private-cloud
    nosqlRef:
      name: electric-anvil-nosql
    objectStorageRefs:
      - name: electric-anvil-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
