apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: golden-cactus-api
spec:
  parameters:
    namespace: guest-golden-cactus
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsSecret: demo4-api-tls
    sqlRef:
      name: golden-cactus-sql
      backend: private-cloud
    nosqlRef:
      name: golden-cactus-nosql
    objectStorageRefs:
      - name: golden-cactus-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
