apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: blazing-pretzel-api
spec:
  parameters:
    namespace: guest-blazing-pretzel
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsSecret: demo3-api-tls
    sqlRef:
      name: blazing-pretzel-sql
      backend: private-cloud
    nosqlRef:
      name: blazing-pretzel-nosql
    objectStorageRefs:
      - name: blazing-pretzel-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
