apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: disco-volcano-api
spec:
  parameters:
    namespace: guest-disco-volcano
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsSecret: demo4-api-tls
    sqlRef:
      name: disco-volcano-sql
      backend: private-cloud
    nosqlRef:
      name: disco-volcano-nosql
    objectStorageRefs:
      - name: disco-volcano-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
