apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: disco-pretzel-api
spec:
  parameters:
    namespace: guest-disco-pretzel
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo5-api.mattjarrett.dev
    tlsSecret: demo5-api-tls
    sqlRef:
      name: disco-pretzel-sql
      backend: private-cloud
    objectStorageRefs:
      - name: disco-pretzel-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
