apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-haunted-taco
spec:
  parameters:
    namespace: guest-haunted-taco
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-haunted-taco
    nosqlRef:
      name: xnosql-haunted-taco
    objectStorageRef:
      name: xobjectstorage-haunted-taco
    cache:
      enabled: true
    readinessCheckPath: /readyz
