apiVersion: platform.local.lab/v1alpha1
kind: XSql
metadata:
  name: xsql-blazing-factory
spec:
  parameters:
    namespace: guest-blazing-factory
    backend: private-cloud
    dataRetention: delete
