apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: blazing-burrito-api
spec:
  parameters:
    namespace: guest-blazing-burrito
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsSecret: demo4-api-tls
    sqlRef:
      name: blazing-burrito-sql
      backend: private-cloud
    nosqlRef:
      name: blazing-burrito-nosql
    objectStorageRefs:
      - name: blazing-burrito-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
