apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-neon-anvil
spec:
  parameters:
    namespace: guest-neon-anvil
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-neon-anvil
    readinessCheckPath: /readyz
