apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: launchpad-api-xr-viewer
rules:
  - apiGroups:
      - platform.local.lab
    resources:
      - xapis
      - xspas
      - xsqls
      - xnosqls
      - xobjectstorages
      - xtopics
      - xsubscriptions
      - xwordpresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apiextensions.crossplane.io
    resources:
      - compositeresourcedefinitions
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: launchpad-api-xr-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: launchpad-api-xr-viewer
subjects:
  - kind: ServiceAccount
    name: launchpad-api
    namespace: launchpad
