apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-atomic-submarine
spec:
  parameters:
    namespace: guest-atomic-submarine
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    readinessCheckPath: /readyz
