apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-velvet-volcano
spec:
  parameters:
    namespace: guest-velvet-volcano
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-velvet-volcano
      backend: private-cloud
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
