apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: frozen-penguin-api
spec:
  parameters:
    namespace: guest-frozen-penguin
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsSecret: demo3-api-tls
    nosqlRef:
      name: frozen-penguin-nosql
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
