apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: frozen-penguin-api
spec:
  parameters:
    namespace: guest-frozen-penguin
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo1-api.mattjarrett.dev
    tlsSecret: demo1-api-tls
    sqlRef:
      name: frozen-penguin-sql
      backend: private-cloud
    nosqlRef:
      name: frozen-penguin-nosql
    objectStorageRefs:
      - name: frozen-penguin-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
