apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: sump-pump-consumer
spec:
  parameters:
    namespace: sump-pump
    image: ghcr.io/cujarrett/sump-pump-consumer:sha-4a8404aa2fab94283acf3420abf992fd5f3c627f
    port: 8080
    scrapeInterval: "10s"
    subscriptionRef:
      name: sump-pump-monitor
