apiVersion: platform.local.lab/v1alpha1
kind: Api
metadata:
  name: sump-pump-consumer
  namespace: sump-pump
spec:
  parameters:
    image: ghcr.io/cujarrett/sump-pump-consumer:sha-4ddd1615fba15c528349516afb0d0c6757743cf0
    repo: https://github.com/cujarrett/sump-pump
    port: 8080
    scrapeInterval: "10s"
    subscriptionRef:
      name: sump-pump-monitor
