apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: sump-pump-bridge
spec:
  parameters:
    namespace: sump-pump
    image: ghcr.io/cujarrett/sump-pump-bridge:sha-6edc953f948a6db268482e55838c058f5cc7fb80
    port: 8080
    host: sump-pump-bridge.local.lab
    tlsIssuer: local-lab-ca-issuer
    topicRef:
      name: home-appliances
    secretRef:
      name: sump-pump-bridge-config
