apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: sump-pump-bridge
spec:
  parameters:
    namespace: sump-pump
    image: ghcr.io/cujarrett/sump-pump-bridge:sha-29f9c0cc7a69f4d0d3c1500ba0c291f864c3377c
    repo: https://github.com/cujarrett/sump-pump-bridge
    port: 8080
    host: sump-pump-bridge.local.lab
    tlsIssuer: local-lab-ca-issuer
    topicRef:
      name: home-appliances
    secretRef:
      name: sump-pump-bridge-config
