apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: sump-pump-bridge
spec:
  parameters:
    namespace: sump-pump
    image: ghcr.io/cujarrett/sump-pump-bridge:sha-0cc65cf581088d105b9d8546778fa197668d9e7f
    repo: https://github.com/cujarrett/sump-pump-bridge
    port: 8080
    host: sump-pump-bridge.local.lab
    tlsIssuer: local-lab-ca-issuer
    topicRef:
      name: home-appliances
    secretRef:
      name: sump-pump-bridge-config
