apiVersion: platform.local.lab/v1alpha1
kind: XSubscription
metadata:
  name: sump-pump-monitor
spec:
  parameters:
    topicRef:
      name: home-appliances
    filterSubject: "home.appliance.sump-pump.>"
    deliverPolicy: new
    ackPolicy: explicit
