apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: weather-exporter
spec:
  parameters:
    namespace: sump-pump
    image: ghcr.io/cujarrett/weather-exporter:sha-6147968dc1483d2139f440e8056de88fd154f915
    port: 8080
    metricsPort: 8080
