apiVersion: platform.local.lab/v1alpha1
kind: XSpa
metadata:
  name: xspa-phantom-penguin
spec:
  parameters:
    namespace: guest-phantom-penguin
    image: ghcr.io/cujarrett/hello-world-spa:latest
    host: demo2.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    replicas: 1
