apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-turbo-cassette
spec:
  parameters:
    namespace: guest-turbo-cassette
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    readinessCheckPath: /readyz
