apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: cosmic-cactus-api
spec:
  parameters:
    namespace: guest-cosmic-cactus
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo2-api.mattjarrett.dev
    tlsSecret: demo2-api-tls
    sqlRef:
      name: cosmic-cactus-sql
      backend: private-cloud
    nosqlRef:
      name: cosmic-cactus-nosql
    objectStorageRefs:
      - name: cosmic-cactus-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
