apiVersion: platform.local.lab/v1alpha1
kind: XSpa
metadata:
  name: xspa-magic-burrito
spec:
  parameters:
    namespace: guest-magic-burrito
    image: ghcr.io/cujarrett/hello-world-spa:latest
    host: demo1.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    replicas: 1
