apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: golden-hamster-api
spec:
  parameters:
    namespace: guest-golden-hamster
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo2-api.mattjarrett.dev
    tlsSecret: demo2-api-tls
    sqlRef:
      name: golden-hamster-sql
      backend: private-cloud
    nosqlRef:
      name: golden-hamster-nosql
    objectStorageRefs:
      - name: golden-hamster-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
