apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: my-vinyl-api
spec:
  parameters:
    namespace: my-vinyl
    image: ghcr.io/cujarrett/my-vinyl-api:sha-89cca1122dcc7cf0e8902f59909394fa7dcce4b6
    repo: https://github.com/cujarrett/my-vinyl-api
    port: 8080
    replicas: 1
    host: my-vinyl-api.local.lab
    tlsIssuer: local-lab-ca-issuer
    secretRef:
      name: discogs-credentials
    cache:
      enabled: true
      backend: private-cloud
