apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: my-vinyl-api
spec:
  parameters:
    namespace: my-vinyl
    image: ghcr.io/cujarrett/my-vinyl-api:sha-a6917dd606b9f3706edf195d396b240614c44a21
    port: 8080
    host: my-vinyl-api.local.lab
    tlsIssuer: local-lab-ca-issuer
    environment: test
    cache:
      enabled: true
    secretRef:
      name: discogs-credentials
