apiVersion: platform.local.lab/v1alpha1
kind: XSpa
metadata:
  name: my-vinyl
spec:
  parameters:
    namespace: my-vinyl
    image: ghcr.io/cujarrett/my-vinyl:sha-926d05ad2438acb90c73f3a92db994302c0cf985
    repo: https://github.com/cujarrett/my-vinyl
    host: myvinyl.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    contentSecurityPolicy: "default-src 'self'; connect-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://i.discogs.com; frame-ancestors 'none'; base-uri 'self';"
    replicas: 1
    size: sm
    apiProxy:
      enabled: true
      upstream: my-vinyl-api.my-vinyl.svc.cluster.local
