apiVersion: platform.local.lab/v1alpha1
kind: Api
metadata:
  name: my-vinyl-api
  namespace: my-vinyl
spec:
  parameters:
    image: ghcr.io/cujarrett/my-vinyl-api:sha-4ef288c8762d9904d48b0bd8bfe4873318d9ae9e
    repo: https://github.com/cujarrett/my-vinyl-api
    port: 8080
    replicas: 1
    host: my-vinyl-api.local.lab
    tlsIssuer: local-lab-ca-issuer
    secretsFrom: [discogs-credentials]
    cache:
      enabled: true
      backend: private-cloud
    consumes:
      - { host: api.discogs.com }
