apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-frozen-waffle
spec:
  parameters:
    namespace: guest-frozen-waffle
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo2-api.mattjarrett.dev
    tlsSecret: demo2-api-tls
    readinessCheckPath: /readyz
