apiVersion: platform.local.lab/v1alpha1
kind: XSpa
metadata:
  name: mattjarrett-dev
spec:
  parameters:
    namespace: mattjarrett-dev
    image: ghcr.io/cujarrett/mattjarrett.dev:sha-54f7c37df35e181df88a22a2e64b5c78828ee68f
    repo: https://github.com/cujarrett/mattjarrett.dev
    host: mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    contentSecurityPolicy: "default-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data:; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self';"
    replicas: 1
    size: sm
