apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-quantum-factory
spec:
  parameters:
    namespace: guest-quantum-factory
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo3-api.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    sqlRef:
      name: xsql-quantum-factory
    cache:
      enabled: true
    readinessCheckPath: /readyz
