apiVersion: platform.local.lab/v1alpha1
kind: XSpa
metadata:
  name: xspa-quantum-factory
spec:
  parameters:
    namespace: guest-quantum-factory
    image: ghcr.io/cujarrett/hello-world-spa:latest
    host: demo3.mattjarrett.dev
    tlsIssuer: letsencrypt-prod
    replicas: 1
