apiVersion: platform.local.lab/v1alpha1
kind: XSql
metadata:
  name: midnight-pretzel-sql
spec:
  parameters:
    namespace: guest-midnight-pretzel
    backend: private-cloud
    dataRetention: delete
