apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: laser-llama-api
spec:
  parameters:
    namespace: guest-laser-llama
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo2-api.mattjarrett.dev
    tlsSecret: demo2-api-tls
    sqlRef:
      name: laser-llama-sql
      backend: private-cloud
    nosqlRef:
      name: laser-llama-nosql
    objectStorageRefs:
      - name: laser-llama-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
