apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: xapi-rubber-cactus
spec:
  parameters:
    namespace: guest-rubber-cactus
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsSecret: demo4-api-tls
    nosqlRef:
      name: xnosql-rubber-cactus
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
