apiVersion: platform.local.lab/v1alpha1
kind: XApi
metadata:
  name: frozen-cannon-api
spec:
  parameters:
    namespace: guest-frozen-cannon
    image: ghcr.io/cujarrett/hello-world-api:latest
    port: 8080
    replicas: 1
    host: demo4-api.mattjarrett.dev
    tlsSecret: demo4-api-tls
    sqlRef:
      name: frozen-cannon-sql
      backend: private-cloud
    nosqlRef:
      name: frozen-cannon-nosql
    objectStorageRefs:
      - name: frozen-cannon-store
    cache:
      enabled: true
      backend: private-cloud
    readinessCheckPath: /readyz
